In [25]:
import pandas as pd
import numpy as np
from sklearn import preprocessing, model_selection, neighbors

In [26]:
df = pd.read_csv('breast-cancer-wisconsin.data')
df.replace('?', -99999, inplace=True)
df.drop(['id'], 1, inplace=True)
df.head(20)

,clump_thickness,uniform_cell_size,uniform_cell_shape,marginal_adhesion,single_epi_cell_size,bare_nuclei,bland_chrom,normal_nucleoli,mitoses,class
0,5,1,1,1,2,1,3,1,1,2
1,5,4,4,5,7,10,3,2,1,2
2,3,1,1,1,2,2,3,1,1,2
3,6,8,8,1,3,4,3,7,1,2
4,4,1,1,3,2,1,3,1,1,2
5,8,10,10,8,7,10,9,7,1,4
6,1,1,1,1,2,10,3,1,1,2
7,2,1,2,1,2,1,3,1,1,2
8,2,1,1,1,2,1,1,1,5,2
9,4,2,1,1,2,1,2,1,1,2
10,1,1,1,1,1,1,3,1,1,2
11,2,1,1,1,2,1,2,1,1,2
12,5,3,3,3,2,3,4,4,1,4
13,1,1,1,1,2,3,3,1,1,2
14,8,7,5,10,7,9,5,5,4,4
15,7,4,6,4,6,1,4,3,1,4
16,4,1,1,1,2,1,2,1,1,2
17,4,1,1,1,2,1,3,1,1,2
18,10,7,7,6,4,10,4,1,2,4
19,6,1,1,1,2,1,3,1,1,2

In [23]:
X = np.array(df.drop(['class'], 1))
y = np.array(df['class'])

X_train, X_test, y_train, y_test = model_selection.train_test_split(X,y,test_size=0.2)

clf = neighbors.KNeighborsClassifier()
clf.fit(X_train, y_train)

accuracy = clf.score(X_test, y_test)
print(accuracy)

0.9642857142857143

In [27]:
example_measures = np.array([8,3,3,2,1,3,4,7,3])
example_measures = example_measures.reshape(len(example_measures),-1)
prediction = clf.predict(example_measures)
print(prediction)

[4]